### Existem diversos objetos python (classes) para manipularem diferentes tipos de dados

### Já aprendemos listas e suas operações, vamos rever, aqui

In [1]:
import os, sys
import pandas as pd # pandas e seu alias pd
import numpy as np  # numpy  e seu alias np

import matplotlib.pyplot as plt # matplotlib e seu alias plt
%matplotlib inline

### Lista e arrays apesar de serem muito similares, se comportam de modo diferente

  - lista pode contem objetos diferentes
  - numpy arrays somente dados de mesmo tipo

In [2]:
lista = ['a', 'casa', 1, 3, 8, 2.345, True, False]
len(lista)

8

### se você trasnformar uma lista heterogênea qto a tipo de dados o np.array faz uma coerção para \<string>

In [3]:
np.array(lista)

array(['a', 'casa', '1', '3', '8', '2.345', 'True', 'False'], dtype='<U5')

### Adição e multiplicação de listas e np.arrays são diferentes

In [4]:
l1 = [1, 2, 3, 4, 5]
type(l1), l1

(list, [1, 2, 3, 4, 5])

In [5]:
l2 = [4, 5, 6, 7, 8]
l1 + l2, len(l1 + l2)

([1, 2, 3, 4, 5, 4, 5, 6, 7, 8], 10)

In [6]:
arr1 = np.array(l1)
arr2 = np.array(l2)

arr1 + arr2, len(arr1 + arr2)

(array([ 5,  7,  9, 11, 13]), 5)

### Multiplicação

In [7]:
l1 * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
arr1 * 3

array([ 3,  6,  9, 12, 15])

### Como ordenar listas ou arrays?

In [9]:
# lorg = lista organizada, inicialmente desorganizada
lorg = [1, 3, 0, 9, -8, 40, 32, 7, 122, 98]
#-- nada aconteceu?
lorg.sort()

In [10]:
# aha .... o python organiza a lista sem retornar um objeto
lorg

[-8, 0, 1, 3, 7, 9, 32, 40, 98, 122]

### Escreva 'lorg.'' e dê um \<tab>

lorg.\<tab>

In [11]:
type(lorg)

list

### lorg é da classe list e para acessar seus métodos escreve-se \<objeto>.metodo()

In [12]:
lorg.remove(3)
lorg

[-8, 0, 1, 7, 9, 32, 40, 98, 122]

In [13]:
# deu erro??? porque?
# lorg.remove(3)

### Ordenando um np.array

In [14]:
arr = np.array([1, 3, 0, 9, -8, 40, 32, 7, 122, 98])
type(arr), arr

(numpy.ndarray, array([  1,   3,   0,   9,  -8,  40,  32,   7, 122,  98]))

In [15]:
arr.sort()

In [16]:
arr

array([ -8,   0,   1,   3,   7,   9,  32,  40,  98, 122])

### Posso ordenar uma lista com um operador Numpy e se trasnformará em objeto numpy

In [17]:
lorg = [1, 3, 0, 9, -8, 40, 32, 7, 122, 98]
print(type(lorg))

#-- aqui uso o operador numpy.sort()
lorg = np.sort(lorg)
type(lorg), lorg

<class 'list'>


(numpy.ndarray, array([ -8,   0,   1,   3,   7,   9,  32,  40,  98, 122]))

### Porque usar numpy?

In [18]:
a = np.arange(0, 10e6, 1)
len(a), type(a)

(10000000, numpy.ndarray)

In [19]:
# coerção de a para lista
b = list(a)
len(b), type(b)

(10000000, list)

### Usando datetime, time .... aqui só time

In [20]:
import time

seconds = time.time()
print("Seconds since epoch =", seconds)

Seconds since epoch = 1600457885.456594


In [21]:
tini = time.time()
for i in range(1000):
    pass

tend = time.time()

print("Seconds for the above loop %.5f ms"%( (tend-tini)*1000) )

Seconds for the above loop 0.36097 ms


In [22]:
tini = time.time()
a = 3

for i in range(1000):
    a = a + 3

tend = time.time()

print("Seconds for the above loop %.5f ms"%( (tend-tini)*1000) )

Seconds for the above loop 0.40960 ms


In [23]:
tini = time.time()
a = 3

for i in range(1000):
    a += 3

tend = time.time()

print("Seconds for the above loop %.5f ms"%( (tend-tini)*1000) )

Seconds for the above loop 0.20266 ms


### Ganhando em complexidade demora mais tempo ...

In [24]:
import math

tini = time.time()
a = 3

for i in range(1000):
    a = (a*5 + math.log(a)) /2

tend = time.time()

print("Seconds for the above loop %.5f ms"%( (tend-tini)*1000) )

Seconds for the above loop 1.37329 ms


### Vamos embaralhar os dados

In [25]:
a = np.arange(0, 8, 1)
np.random.shuffle(a)
a

array([2, 1, 6, 0, 5, 7, 4, 3])

### Vamos medir o tempo do sort de uma lista e do numpy

100 milhoẽs de inteiros !!

não é muito trivial criar e embaralhar 100 milhões de inteiros, pode tomar alguns segundos

reduzindo para 1 milhão 

In [26]:
a = np.arange(0, 1e6, 1)
len(a), type(a)

(1000000, numpy.ndarray)

In [27]:
tempos = []

for i in range(6):
    tini = time.time()
    np.random.shuffle(a)
    a.sort()
    tend = time.time()

    delta = (tend-tini)*1000
    print("Loop %d) segundos para organizar  %d números inteiros em %s = %.5f ms"%(i, len(a), type(a), delta) )
    
    tempos.append(delta)

np.mean(tempos), np.std(tempos)

Loop 0) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 88.10091 ms
Loop 1) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 82.50809 ms
Loop 2) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 81.20823 ms
Loop 3) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 81.44188 ms
Loop 4) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 82.78441 ms
Loop 5) segundos para organizar  1000000 números inteiros em <class 'numpy.ndarray'> = 81.18868 ms


(82.87203311920166, 2.4196609620162057)

### Agora uma lista, vamos fazer uma coerção de array para lista

In [28]:
tempos = []

for i in range(6):
    tini = time.time()
    np.random.shuffle(a)
    alist = list(a)
    alist.sort()
    tend = time.time()

    delta = (tend-tini)*1000
    print("Loop %d) segundos para organizar  %d números inteiros em %s = %.5f ms"%(i, len(alist), type(alist), delta) )
    
    tempos.append(delta)

np.mean(tempos), np.std(tempos)

Loop 0) segundos para organizar  1000000 números inteiros em <class 'list'> = 629.64106 ms
Loop 1) segundos para organizar  1000000 números inteiros em <class 'list'> = 805.16934 ms
Loop 2) segundos para organizar  1000000 números inteiros em <class 'list'> = 843.69087 ms
Loop 3) segundos para organizar  1000000 números inteiros em <class 'list'> = 820.24121 ms
Loop 4) segundos para organizar  1000000 números inteiros em <class 'list'> = 836.51042 ms
Loop 5) segundos para organizar  1000000 números inteiros em <class 'list'> = 826.22433 ms


(793.5795386632284, 74.32012183019081)

### O numpy está otimizado em linguagem C e é muito mais rápidos
### Sempre trabalhe com o numpy, vermos nas próximas aulas ...

## Outros tipos de estrutura de dados

### Tuples

são listas fixas, repare que o próprio eco do Notebook é uma tuple

In [29]:
tup = (2, 3, 5)
type(tup), len(tup), tup

(tuple, 3, (2, 3, 5))

### Sets

são listas com dados que nunca sem repetem

In [30]:
l1, l2, l1+l2

([1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [31]:
lset = set(l1 + l2)
type(lset), lset

(set, {1, 2, 3, 4, 5, 6, 7, 8})

### Diferença, União e Intersecção

Operações utilizadas para se construir um diagrama de Venn

In [32]:
a = set(["a", "b", "c", "a"])
b = set(["a", "b", "c", "d", "e"])

In [33]:
a.difference(b)

set()

In [34]:
b.difference(a)

{'d', 'e'}

In [35]:
b.union(a)

{'a', 'b', 'c', 'd', 'e'}

In [36]:
b.union(a)  == b

True

In [37]:
b.union(a) == a

False

In [38]:
b.intersection(a)

{'a', 'b', 'c'}

In [39]:
a.intersection(b)

{'a', 'b', 'c'}

### Dicionário (dictionary)
### dict() == {}

Este é quem sabe o objeto mais usado no Python  
neste curso não entraremos a fundo do porquê  
mas, veremos aqui o como ele é útil  
ele é importante para gerarmos dados e transformarmos em tabelas Pandas

In [40]:
dic = {}
dic['carro'] = 1000
dic['bicicleta'] = 20
dic['saco de arroz'] = 10
dic['caneta'] = 0.01

type(dic)

dict

In [41]:
dic

{'carro': 1000, 'bicicleta': 20, 'saco de arroz': 10, 'caneta': 0.01}

### o método keys() --> gera uma lista de chaves

In [42]:
dic.keys()

dict_keys(['carro', 'bicicleta', 'saco de arroz', 'caneta'])

### o método values() --> gera uma lista de valores

In [43]:
dic.values()

dict_values([1000, 20, 10, 0.01])

In [44]:
for k in dic.keys():
    print('\t', k, '\t',dic[k])

	 carro 	 1000
	 bicicleta 	 20
	 saco de arroz 	 10
	 caneta 	 0.01


### Iterador items()

In [45]:
for k, val in dic.items():
    print('\t',k, '\t',val)

	 carro 	 1000
	 bicicleta 	 20
	 saco de arroz 	 10
	 caneta 	 0.01


### Ao invés de um valor, uma lista de valores

In [46]:
dic = {}
dic['carro'] = [1000, 'kg']
dic['bicicleta'] = [20, 'kg']
dic['saco de arroz'] = [10, 'kg']
dic['caneta'] = [10, 'g']

len(dic.keys())

4

In [47]:
for k, val in dic.items():
    print('\t',k, '\t',val)

	 carro 	 [1000, 'kg']
	 bicicleta 	 [20, 'kg']
	 saco de arroz 	 [10, 'kg']
	 caneta 	 [10, 'g']


In [48]:
for k, val in dic.items():
    print('\t',k, '\t peso = ',val[0], val[1])

	 carro 	 peso =  1000 kg
	 bicicleta 	 peso =  20 kg
	 saco de arroz 	 peso =  10 kg
	 caneta 	 peso =  10 g


In [49]:
for k, val in dic.items():
    print("Objeto %s, tem peso %d %s" %(k, val[0], val[1]) )

Objeto carro, tem peso 1000 kg
Objeto bicicleta, tem peso 20 kg
Objeto saco de arroz, tem peso 10 kg
Objeto caneta, tem peso 10 g
