### Um vetor, matriz de 1 dimensão = lista em Python

In [1]:
mat = [2,3,4, 5, 6, 7]

In [3]:
mat

[2, 3, 4, 5, 6, 7]

In [5]:
len(mat)

6

o Python começa contar do zero

In [7]:
mat[0]

2

In [8]:
mat[-1]

7

### Em Python, uma lista é muito versátil

In [9]:
m2 = [1, 2, 3.5, 1/3, 'a', 'como vai você?']

In [10]:
m2

[1, 2, 3.5, 0.3333333333333333, 'a', 'como vai você?']

In [11]:
m2[0]

1

In [12]:
type(m2[0])

int

### Veja como é fácil um loop (laço)

In [13]:
for m in m2:
    print(m)

1
2
3.5
0.3333333333333333
a
como vai você?


In [16]:
# \t == tabulador
# type() - é para achar o tipo de objeto

for m in m2:
    print(m, '\t', type(m))

1 	 <class 'int'>
2 	 <class 'int'>
3.5 	 <class 'float'>
0.3333333333333333 	 <class 'float'>
a 	 <class 'str'>
como vai você? 	 <class 'str'>


### O Python às vezes faz mágica!

In [17]:
mat 

[2, 3, 4, 5, 6, 7]

In [18]:
mat * 3

[2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7]

In [19]:
# isto não fucniona !
mat + 1

TypeError: can only concatenate list (not "int") to list

In [26]:
mat2 = [10, 11, 12, 13, 14, 15]
mat, mat2

([2, 3, 4, 5, 6, 7], [10, 11, 12, 13, 14, 15])

In [27]:
mat + mat2

[2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]

### Existe uma biblioteca para manipular matrizes e cálculo com números
  - Numpy: https://numpy.org/

In [21]:
### Chamando um biblioteca em python (ou pacote = package)
import numpy as np

In [22]:
matn = np.array(mat)

In [23]:
matn

array([2, 3, 4, 5, 6, 7])

In [24]:
matn * 3

array([ 6,  9, 12, 15, 18, 21])

In [25]:
matn + 1

array([3, 4, 5, 6, 7, 8])

In [28]:
matn2 = np.array(mat2)
matn, matn2

(array([2, 3, 4, 5, 6, 7]), array([10, 11, 12, 13, 14, 15]))

In [29]:
matn + matn2

array([12, 14, 16, 18, 20, 22])

### Como você pode obsevar uma LISTA tem um comportamento diferente que uma Lista em Numpy