In [84]:
# def fulfilGaps(self, seqs):
import numpy as np

seqs = np.array([ ["A","C","G","T"], ["C","C","G","T"], ["-","-","G","T"], ["A","C","A","T"],
                  ["-","-","G","T"], ["-","-","G","T"], ["-","-","G","T"], 
                  ["G","C","A","T"], ["G","C","G","T"], ["A","C","G","T"], ["A","C","G","T"]])
numOfLetters=1
ncol = seqs.shape[1]
nrow = seqs.shape[0]
maxL = ncol-numOfLetters+1

dicPiList = []
dicLeList = []

for j in range(maxL):
    dicPi = {}; dicLe = {}

    for row in range(nrow):
        letters = "".join(seqs[row,j:(j+numOfLetters)])
        try:
            dicPi[letters] += 1
            dicLe[letters] += 1
        except:
            dicPi[letters] = 1
            dicLe[letters] = 1

    for key in dicPi.keys():
        dicPi[key] /= nrow
        print(j, key, dicPi[key])
        
    dicPiList.append(dicPi)
    dicLeList.append(dicLe)

print("")
for j in range(maxL):
    dicPi = dicPiList[j]
    dicLe = dicLeList[j]
    
    if len(dicPi.keys()) > 1:
        if "-" in dicPi.keys():
            if len(dicPi.keys()) == 2:
                mat = list(dicPi.keys())
                mat = list(filter(lambda x : x != '-', mat))
                for row in range(nrow):
                    if "".join(seqs[row,j:(j+numOfLetters)]) == "-"*numOfLetters:
                        seqs[row,j:(j+numOfLetters)] = mat[0]
            else:
                ntrace = dicLe['-']
                matRep = [ntrace]
                
                del dicPi["-"]
                del dicLe["-"]
                total = sum(dicPi.values())
                for key in dicPi.keys():
                    dicPi[key] /= total
                    # dicLe[key] /= total
                    print(j, key, dicPi[key])
                
                
                mat = list(dicPi.keys())
                mat = list(filter(lambda x : x != '-', mat))
                
                pis=[];vals=[]; reps=[]; lets=[]
                for key in dicPi.keys():
                    pis.append(dicPi[key])
                    vals.append(dicLe[key])
                    
                    n = round(dicPi[key] * dicLe[key])
                    print("n   ", n, dicPi[key] * dicLe[key], dicPi[key], dicLe[key])
                    reps.append(n)
                    lets += n*[key]
                
                print("lets", len(lets), "ntrace", ntrace, "mat", mat)
                if len(lets) < ntrace:
                    #reps[0] += 1
                    lets.append(lets[0])
                    
                print(pis)
                print(vals)
                print(reps)
                print(lets)
                print("----------------------------")
                print("")
                
                count = 0
                for row in range(nrow):
                    if "".join(seqs[row,j:(j+numOfLetters)]) == "-"*numOfLetters:
                        seqs[row,j:(j+numOfLetters)] = lets[count]
                        count += 1
        

print(seqs)

0 A 0.36363636363636365
0 C 0.09090909090909091
0 - 0.36363636363636365
0 G 0.18181818181818182
1 C 0.6363636363636364
1 - 0.36363636363636365
2 G 0.8181818181818182
2 A 0.18181818181818182
3 T 1.0

0 A 0.5714285714285714
0 C 0.14285714285714285
0 G 0.2857142857142857
n    2 2.2857142857142856 0.5714285714285714 4
n    0 0.14285714285714285 0.14285714285714285 1
n    1 0.5714285714285714 0.2857142857142857 2
lets 3 ntrace 4 mat ['A', 'C', 'G']
[0.5714285714285714, 0.14285714285714285, 0.2857142857142857]
[4, 1, 2]
[2, 0, 1]
['A', 'A', 'G', 'A']
----------------------------

[['A' 'C' 'G' 'T']
 ['C' 'C' 'G' 'T']
 ['A' 'C' 'G' 'T']
 ['A' 'C' 'A' 'T']
 ['A' 'C' 'G' 'T']
 ['G' 'C' 'G' 'T']
 ['A' 'C' 'G' 'T']
 ['G' 'C' 'A' 'T']
 ['G' 'C' 'G' 'T']
 ['A' 'C' 'G' 'T']
 ['A' 'C' 'G' 'T']]


In [21]:
x = ['ala@ala.com', 'bala@bala.com']
x.remove('ala@ala.com')
x

['bala@bala.com']

In [26]:
mat = ['-', 'A']
mat = list(filter(lambda x : x != '-', mat))
print(mat)

['A']


In [ ]:
def fulfill2(seqs2, numOfLetters=1):
    seqs = copy.deepcopy(seqs2)
    ncol = seqs.shape[1]
    nrow = seqs.shape[0]
    maxL = ncol-numOfLetters+1

    dicPiList = []
    dicLeList = []

    for j in range(maxL):
        dicPi = {}; dicLe = {}

        for row in range(nrow):
            letters = "".join(seqs[row,j:(j+numOfLetters)])
            try:
                dicPi[letters] += 1
                dicLe[letters] += 1
            except:
                dicPi[letters] = 1
                dicLe[letters] = 1

        for key in dicPi.keys():
            dicPi[key] /= nrow
            # print(j, key, dicPi[key])

        dicPiList.append(dicPi)
        dicLeList.append(dicLe)


    for j in range(maxL):
        dicPi = dicPiList[j]
        dicLe = dicLeList[j]

        if len(dicPi.keys()) > 1:
            if "-" in dicPi.keys():
                if len(dicPi.keys()) == 2:
                    print("in2 ", j)
                    mat = list(dicPi.keys())
                    mat = list(filter(lambda x : x != '-', mat))
                    for row in range(nrow):
                        if "".join(seqs[row,j:(j+numOfLetters)]) == "-"*numOfLetters:
                            seqs[row,j:(j+numOfLetters)] = mat[0]
                else:
                    print("inMany ", j)
                    ntrace = dicLe['-']
                    matRep = [ntrace]

                    del dicPi["-"]
                    del dicLe["-"]
                    total = sum(dicPi.values())
                    for key in dicPi.keys():
                        dicPi[key] /= total
                        # dicLe[key] /= total
                        print(j, key, dicPi[key])


                    mat = list(dicPi.keys())
                    mat = list(filter(lambda x : x != '-', mat))

                    pis=[];vals=[]; reps=[]; lets=[]
                    for key in dicPi.keys():
                        pis.append(dicPi[key])
                        vals.append(dicLe[key])

                        n = round(dicPi[key] * dicLe[key])
                        # print("n   ", n, dicPi[key] * dicLe[key], dicPi[key], dicLe[key])
                        reps.append(n)
                        lets += n*[key]

                    # print("lets", len(lets), "ntrace", ntrace, "mat", mat)
                    if len(lets) < ntrace:
                        #reps[0] += 1
                        lets.append(lets[0])


                    count = 0
                    for row in range(nrow):
                        if "".join(seqs[row,j:(j+numOfLetters)]) == "-"*numOfLetters:
                            seqs[row,j:(j+numOfLetters)] = lets[count]
                            count += 1

    return seqs

In [ ]:
["".join(seqx) for seqx in seqs6[0:120,7:25]]

seqsqq = fulfill2(seqs6[0:120,0:55], numOfLetters=1)
["".join(seqx) for seqx in seqsqq]

### Test

In [ ]:
a = [1,2,3]
b = [3,4,5]
print(a+b)

In [85]:
import numpy as np

In [86]:
A = np.random.randint(5, size=(10,3))
A

array([[1, 1, 3],
       [4, 0, 1],
       [4, 3, 3],
       [3, 0, 0],
       [4, 1, 4],
       [1, 1, 4],
       [3, 3, 3],
       [4, 2, 0],
       [3, 1, 1],
       [3, 1, 0]])

In [88]:
np.random.choice(A.shape[0], 5, replace=False)

array([2, 0, 7, 6, 9])

In [90]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [95]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])